- name: pull frontend image
  docker_container:
    name: frontend
    image: "hubrudcontainerregistry.azurecr.io/frontend:latest"
    state: started
    restart_policy: always
    ports:
      - "80:80"