pipeline {
    agent any

    environment {
        ACR_NAME = "hubrudcontainerregistry.azurecr.io"
        IMAGE_NAME = "frontend"
    }

    stages {

        stage('Build Frontend Image') {
            steps {
                dir('services/frontend') {
                    sh '''
                    docker build -t $ACR_NAME/$IMAGE_NAME:latest .
                    '''
                }
            }
        }

        stage('Login to ACR') {
            steps {
                sh '''
                az acr login --name hubrudcontainerregistry
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push $ACR_NAME/$IMAGE_NAME:latest
                '''
            }
        }

        stage('Generate Ansible Inventory') {
            steps {
                script {

                    env.DEV1_IP = sh(
                        script: "cd terraform/dev-1 && terraform output -raw dev1_public_ip -no-color",
                        returnStdout: true
                    ).trim()

                    sh """
printf "[dev1]\\n%s ansible_user=azureuser\\n" "${env.DEV1_IP}" > ansible/inventory/hosts.ini
"""
                }
            }
        }

        stage('Deploy via Ansible') {
            steps {
                sshagent(credentials: ['azure-vm-key']) {
                    dir('ansible') {
                        sh '''
                        ansible-playbook playbooks/dev1-playbook.yml
                        '''
                    }
                }
            }
        }

    }
}