pipeline {
    agent any

    environment {
        ACR_NAME = "hubrudcontainerregistry.azurecr.io"
        IMAGE_NAME = "frontend"
    }

    stages {

        stage('Fetch Backend IP') {
            steps {
                script {

                    env.BACKEND_IP = sh(
                        script: """
                            cd terraform/dev-2
                            terraform init -input=false >/dev/null
                            terraform output -raw dev2_public_ip
                        """,
                        returnStdout: true
                    ).trim()

                    echo "Backend IP: ${env.BACKEND_IP}"
                }
            }
        }

        stage('Inject Backend IP into Nginx') {
            steps {
                dir('services/frontend') {
                    sh """
                    cp nginx.conf nginx.generated.conf
                    sed -i 's|BACKEND_IP|${BACKEND_IP}|g' nginx.generated.conf
                    """
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('services/frontend') {
                    sh '''
                    docker build --platform linux/amd64 -t $ACR_NAME/$IMAGE_NAME:latest .
                    '''
                }
            }
        }

        stage('Login to ACR') {
            steps {
                sh '''
                az acr login --name hubrudcontainerregistry
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push $ACR_NAME/$IMAGE_NAME:latest
                '''
            }
        }

        stage('Generate Ansible Inventory') {
            steps {
                script {
                    def frontendIP = sh(
                        script: 'cd terraform/dev-1 && terraform output -raw dev1_public_ip',
                        returnStdout: true
                    ).trim()

                    sh """
                    echo "[dev1]" > ansible/inventory/hosts.ini
                    echo "${frontendIP} ansible_user=azureuser" >> ansible/inventory/hosts.ini
                    """

                    echo "Frontend IP: ${frontendIP}"
                }
            }
        }

        stage('Deploy via Ansible') {
            steps {
                sshagent(credentials: ['azure-vm-key']) {
                    dir('ansible') {
                        sh '''
                        ansible-playbook playbooks/dev1-playbook.yml
                        '''
                    }
                }
            }
        }

    }
}