pipeline {
    agent any

    environment {
        ACR_NAME = "hubrudcontainerregistry.azurecr.io"
        IMAGE_NAME = "frontend"
    }

    stages {

        stage('Build Frontend Image') {
            steps {
                dir('services/frontend') {
                    sh '''
                    docker build -t $ACR_NAME/$IMAGE_NAME:latest .
                    '''
                }
            }
        }

        stage('Login to ACR') {
            steps {
                sh '''
                az acr login --name hubrudcontainerregistry
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push $ACR_NAME/$IMAGE_NAME:latest
                '''
            }
        }

        stage('Deploy via Ansible') {
            steps {
                dir('ansible') {
                    sh '''
                    ansible-playbook playbooks/dev1-playbook.yml
                    '''
                }
            }
        }

    }
}