pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Terraform Version') {
            steps {
                sh 'terraform -version'
            }
        }

        stage('Terraform Deploy') {
            steps {

                withCredentials([
                    azureServicePrincipal(
                        credentialsId: 'azure-service-principal',
                        subscriptionIdVariable: 'ARM_SUBSCRIPTION_ID',
                        clientIdVariable: 'ARM_CLIENT_ID',
                        clientSecretVariable: 'ARM_CLIENT_SECRET',
                        tenantIdVariable: 'ARM_TENANT_ID'
                    )
                ]) {

                    sh '''
                    export ARM_CLIENT_ID=$ARM_CLIENT_ID
                    export ARM_CLIENT_SECRET=$ARM_CLIENT_SECRET
                    export ARM_SUBSCRIPTION_ID=$ARM_SUBSCRIPTION_ID
                    export ARM_TENANT_ID=$ARM_TENANT_ID
                    '''

                    dir('terraform/dev-1') {
                        sh '''
                        terraform init
                        terraform fmt
                        terraform validate
                        terraform plan
                        terraform apply -auto-approve
                        '''
                    }

                    dir('terraform/dev-2') {
                        sh '''
                        terraform init
                        terraform fmt
                        terraform validate
                        terraform plan
                        terraform apply -auto-approve
                        '''
                    }

                    dir('terraform/hub') {
                        sh '''
                        terraform init
                        terraform fmt
                        terraform validate
                        terraform plan
                        terraform apply -auto-approve
                        '''
                    }

                    dir('terraform/networking') {
                        sh '''
                        terraform init
                        terraform fmt
                        terraform validate
                        terraform plan
                        terraform apply -auto-approve
                        '''
                    }

                }
            }
        }
    }
}