pipeline {
    agent any

    stages {

        stage('Terraform Version') {
            steps {
                sh 'terraform -version'
            }
        }

        stage('Terraform Dev1') {
            steps {
                withCredentials([
                    azureServicePrincipal(
                        credentialsId: 'azure-service-principal',
                        subscriptionIdVariable: 'ARM_SUBSCRIPTION_ID',
                        clientIdVariable: 'ARM_CLIENT_ID',
                        clientSecretVariable: 'ARM_CLIENT_SECRET',
                        tenantIdVariable: 'ARM_TENANT_ID'
                    )
                ]) {

                    dir('terraform/dev-1') {
                        sh '''
                        terraform init
                        terraform fmt
                        terraform validate
                        terraform plan
                        terraform apply -auto-approve
                        '''
                    }

                }
            }
        }

        stage('Terraform Dev2') {
            steps {
                withCredentials([
                    azureServicePrincipal(
                        credentialsId: 'azure-service-principal',
                        subscriptionIdVariable: 'ARM_SUBSCRIPTION_ID',
                        clientIdVariable: 'ARM_CLIENT_ID',
                        clientSecretVariable: 'ARM_CLIENT_SECRET',
                        tenantIdVariable: 'ARM_TENANT_ID'
                    )
                ]) {

                    dir('terraform/dev-2') {
                        sh '''
                        terraform init
                        terraform fmt
                        terraform validate
                        terraform plan
                        terraform apply -auto-approve
                        '''
                    }

                }
            }
        }

        stage('Terraform Hub') {
            steps {
                withCredentials([
                    azureServicePrincipal(
                        credentialsId: 'azure-service-principal',
                        subscriptionIdVariable: 'ARM_SUBSCRIPTION_ID',
                        clientIdVariable: 'ARM_CLIENT_ID',
                        clientSecretVariable: 'ARM_CLIENT_SECRET',
                        tenantIdVariable: 'ARM_TENANT_ID'
                    )
                ]) {

                    dir('terraform/hub') {
                        sh '''
                        terraform init
                        terraform fmt
                        terraform validate
                        terraform plan
                        terraform apply -auto-approve
                        '''
                    }

                }
            }
        }

        stage('Terraform Networking') {
            steps {
                withCredentials([
                    azureServicePrincipal(
                        credentialsId: 'azure-service-principal',
                        subscriptionIdVariable: 'ARM_SUBSCRIPTION_ID',
                        clientIdVariable: 'ARM_CLIENT_ID',
                        clientSecretVariable: 'ARM_CLIENT_SECRET',
                        tenantIdVariable: 'ARM_TENANT_ID'
                    )
                ]) {

                    dir('terraform/networking') {
                        sh '''
                        terraform init
                        terraform fmt
                        terraform validate
                        terraform plan
                        terraform apply -auto-approve
                        '''
                    }

                }
            }
        }
    }
}