- name: run backend container
  community.docker.docker_container:
    name: backend
    image: "hubrudcontainerregistry.azurecr.io/backend:latest"
    state: started
    restart_policy: always
    recreate: true
    pull: true
    ports:
      - "5000:5000"
    env:
      DB_HOST: "{{ sql_server }}"
      DB_NAME: "{{ sql_database }}"
      DB_USER: "{{ sql_username }}@hub-demorudola-sqlserver"
      DB_PASSWORD: "{{ sql_password }}"