---
- name: install python pip
  apt:
    name: python3-pip
    state: present
    update_cache: yes

- name: install docker python sdk
  pip:
    name: docker

- name: pull backend image
  community.docker.docker_image:
    name: hubrudcontainerregistry.azurecr.io/backend:latest
    source: pull

- name: run backend container
  community.docker.docker_container:
    name: backend
    image: hubrudcontainerregistry.azurecr.io/backend:latest
    state: started
    restart_policy: always
    recreate: true
    pull: true
    ports:
      - "5000:5000"
    env:
      DB_HOST: "{{ sql_server }}.database.windows.net"
      DB_NAME: "{{ sql_database }}"
      DB_USER: "{{ sql_username }}"
      DB_PASSWORD: "{{ sql_password }}"