- name: install docker
  apt:
    name: docker.io
    state: present

- name: start docker
  service:
    name: docker
    state: started
    enabled: true

- name: add azureuser to docker group
  user:
    name: azureuser
    groups: docker
    append: yes