- name: update apt cache
  become: yes
  apt:
    update_cache: yes

- name: install docker dependencies
  become: yes
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - software-properties-common
    state: present

- name: install docker
  become: yes
  apt:
    name: docker.io
    state: present

- name: start docker service
  become: yes
  service:
    name: docker
    state: started
    enabled: true

- name: add azureuser to docker group
  become: yes
  user:
    name: azureuser
    groups: docker
    append: yes