pipeline {
    agent any

    environment {
        ACR_NAME = "hubrudcontainerregistry.azurecr.io"
        IMAGE_NAME = "backend"
    }

    stages {

        stage('Build Backend Image') {
            steps {
                dir('services/backend') {
                    sh '''
                    docker build -t $ACR_NAME/$IMAGE_NAME:latest .
                    '''
                }
            }
        }

        stage('Login to ACR') {
            steps {
                sh '''
                az acr login --name hubrudcontainerregistry
                '''
            }
        }

        stage('Push Image') {
            steps {
                sh '''
                docker push $ACR_NAME/$IMAGE_NAME:latest
                '''
            }
        }

        stage('Generate Ansible Inventory') {
            steps {
                script {

                    env.DEV2_IP = sh(
                        script: "cd terraform/dev-2 && terraform output -raw dev2_public_ip -no-color",
                        returnStdout: true
                    ).trim()

                    sh """
cat > ansible/inventory/hosts.ini <<EOF
[dev2]
${env.DEV2_IP} ansible_user=azureuser ansible_ssh_private_key_file=../keys/demo
EOF
"""
                }
            }
        }

        stage('Deploy via Ansible') {
            steps {
                dir('ansible') {
                    sh '''
                    ansible-playbook playbooks/dev2-playbook.yml
                    '''
                }
            }
        }

    }
}